export const timezones = [
    { name: "South Africa (Abidjan)", timezone: "Africa/Abidjan", flag: "🇿🇦" },
    { name: "South Africa (Accra)", timezone: "Africa/Accra", flag: "🇿🇦" },
    { name: "South Africa (Addis Ababa)", timezone: "Africa/Addis_Ababa", flag: "🇿🇦" },
    { name: "South Africa (Algiers)", timezone: "Africa/Algiers", flag: "🇿🇦" },
    { name: "South Africa (Asmara)", timezone: "Africa/Asmara", flag: "🇿🇦" },
    { name: "South Africa (Asmera)", timezone: "Africa/Asmera", flag: "🇿🇦" },
    { name: "South Africa (Bamako)", timezone: "Africa/Bamako", flag: "🇿🇦" },
    { name: "South Africa (Bangui)", timezone: "Africa/Bangui", flag: "🇿🇦" },
    { name: "South Africa (Banjul)", timezone: "Africa/Banjul", flag: "🇿🇦" },
    { name: "South Africa (Bissau)", timezone: "Africa/Bissau", flag: "🇿🇦" },
    { name: "South Africa (Blantyre)", timezone: "Africa/Blantyre", flag: "🇿🇦" },
    { name: "South Africa (Brazzaville)", timezone: "Africa/Brazzaville", flag: "🇿🇦" },
    { name: "South Africa (Bujumbura)", timezone: "Africa/Bujumbura", flag: "🇿🇦" },
    { name: "South Africa (Cairo)", timezone: "Africa/Cairo", flag: "🇿🇦" },
    { name: "South Africa (Casablanca)", timezone: "Africa/Casablanca", flag: "🇿🇦" },
    { name: "South Africa (Ceuta)", timezone: "Africa/Ceuta", flag: "🇿🇦" },
    { name: "South Africa (Conakry)", timezone: "Africa/Conakry", flag: "🇿🇦" },
    { name: "South Africa (Dakar)", timezone: "Africa/Dakar", flag: "🇿🇦" },
    { name: "South Africa (Dar es Salaam)", timezone: "Africa/Dar_es_Salaam", flag: "🇿🇦" },
    { name: "South Africa (Djibouti)", timezone: "Africa/Djibouti", flag: "🇿🇦" },
    { name: "South Africa (Douala)", timezone: "Africa/Douala", flag: "🇿🇦" },
    { name: "South Africa (El Aaiun)", timezone: "Africa/El_Aaiun", flag: "🇿🇦" },
    { name: "South Africa (Freetown)", timezone: "Africa/Freetown", flag: "🇿🇦" },
    { name: "South Africa (Gaborone)", timezone: "Africa/Gaborone", flag: "🇿🇦" },
    { name: "South Africa (Harare)", timezone: "Africa/Harare", flag: "🇿🇦" },
    { name: "South Africa (Johannesburg)", timezone: "Africa/Johannesburg", flag: "🇿🇦" },
    { name: "South Africa (Juba)", timezone: "Africa/Juba", flag: "🇿🇦" },
    { name: "South Africa (Kampala)", timezone: "Africa/Kampala", flag: "🇿🇦" },
    { name: "South Africa (Khartoum)", timezone: "Africa/Khartoum", flag: "🇿🇦" },
    { name: "South Africa (Kigali)", timezone: "Africa/Kigali", flag: "🇿🇦" },
    { name: "South Africa (Kinshasa)", timezone: "Africa/Kinshasa", flag: "🇿🇦" },
    { name: "South Africa (Lagos)", timezone: "Africa/Lagos", flag: "🇿🇦" },
    { name: "South Africa (Libreville)", timezone: "Africa/Libreville", flag: "🇿🇦" },
    { name: "South Africa (Lome)", timezone: "Africa/Lome", flag: "🇿🇦" },
    { name: "South Africa (Luanda)", timezone: "Africa/Luanda", flag: "🇿🇦" },
    { name: "South Africa (Lubumbashi)", timezone: "Africa/Lubumbashi", flag: "🇿🇦" },
    { name: "South Africa (Lusaka)", timezone: "Africa/Lusaka", flag: "🇿🇦" },
    { name: "South Africa (Malabo)", timezone: "Africa/Malabo", flag: "🇿🇦" },
    { name: "South Africa (Maputo)", timezone: "Africa/Maputo", flag: "🇿🇦" },
    { name: "South Africa (Maseru)", timezone: "Africa/Maseru", flag: "🇿🇦" },
    { name: "South Africa (Mbabane)", timezone: "Africa/Mbabane", flag: "🇿🇦" },
    { name: "South Africa (Mogadishu)", timezone: "Africa/Mogadishu", flag: "🇿🇦" },
    { name: "South Africa (Monrovia)", timezone: "Africa/Monrovia", flag: "🇿🇦" },
    { name: "South Africa (Nairobi)", timezone: "Africa/Nairobi", flag: "🇿🇦" },
    { name: "South Africa (Ndjamena)", timezone: "Africa/Ndjamena", flag: "🇿🇦" },
    { name: "South Africa (Niamey)", timezone: "Africa/Niamey", flag: "🇿🇦" },
    { name: "South Africa (Nouakchott)", timezone: "Africa/Nouakchott", flag: "🇿🇦" },
    { name: "South Africa (Ouagadougou)", timezone: "Africa/Ouagadougou", flag: "🇿🇦" },
    { name: "South Africa (Porto-Novo)", timezone: "Africa/Porto-Novo", flag: "🇿🇦" },
    { name: "South Africa (Sao Tome)", timezone: "Africa/Sao_Tome", flag: "🇿🇦" },
    { name: "South Africa (Timbuktu)", timezone: "Africa/Timbuktu", flag: "🇿🇦" },
    { name: "South Africa (Tripoli)", timezone: "Africa/Tripoli", flag: "🇿🇦" },
    { name: "South Africa (Tunis)", timezone: "Africa/Tunis", flag: "🇿🇦" },
    { name: "South Africa (Windhoek)", timezone: "Africa/Windhoek", flag: "🇿🇦" },
    { name: "United States (Adak)", timezone: "America/Adak", flag: "🇺🇸" },
    { name: "United States (Anchorage)", timezone: "America/Anchorage", flag: "🇺🇸" },
    { name: "United States (Anguilla)", timezone: "America/Anguilla", flag: "🇺🇸" },
    { name: "United States (Antigua)", timezone: "America/Antigua", flag: "🇺🇸" },
    { name: "United States (Araguaina)", timezone: "America/Araguaina", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Buenos_Aires", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Catamarca", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/ComodRivadavia", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Cordoba", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Jujuy", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/La_Rioja", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Mendoza", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Rio_Gallegos", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Salta", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/San_Juan", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/San_Luis", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Tucuman", flag: "🇺🇸" },
    { name: "United States (Argentina)", timezone: "America/Argentina/Ushuaia", flag: "🇺🇸" },
    { name: "United States (Aruba)", timezone: "America/Aruba", flag: "🇺🇸" },
    { name: "United States (Asuncion)", timezone: "America/Asuncion", flag: "🇺🇸" },
    { name: "United States (Atikokan)", timezone: "America/Atikokan", flag: "🇺🇸" },
    { name: "United States (Atka)", timezone: "America/Atka", flag: "🇺🇸" },
    { name: "United States (Bahia)", timezone: "America/Bahia", flag: "🇺🇸" },
    { name: "United States (Bahia Banderas)", timezone: "America/Bahia_Banderas", flag: "🇺🇸" },
    { name: "United States (Barbados)", timezone: "America/Barbados", flag: "🇺🇸" },
    { name: "United States (Belem)", timezone: "America/Belem", flag: "🇺🇸" },
    { name: "United States (Belize)", timezone: "America/Belize", flag: "🇺🇸" },
    { name: "United States (Blanc-Sablon)", timezone: "America/Blanc-Sablon", flag: "🇺🇸" },
    { name: "United States (Boa Vista)", timezone: "America/Boa_Vista", flag: "🇺🇸" },
    { name: "United States (Bogota)", timezone: "America/Bogota", flag: "🇺🇸" },
    { name: "United States (Boise)", timezone: "America/Boise", flag: "🇺🇸" },
    { name: "United States (Buenos Aires)", timezone: "America/Buenos_Aires", flag: "🇺🇸" },
    { name: "United States (Cambridge Bay)", timezone: "America/Cambridge_Bay", flag: "🇺🇸" },
    { name: "United States (Campo Grande)", timezone: "America/Campo_Grande", flag: "🇺🇸" },
    { name: "United States (Cancun)", timezone: "America/Cancun", flag: "🇺🇸" },
    { name: "United States (Caracas)", timezone: "America/Caracas", flag: "🇺🇸" },
    { name: "United States (Catamarca)", timezone: "America/Catamarca", flag: "🇺🇸" },
    { name: "United States (Cayenne)", timezone: "America/Cayenne", flag: "🇺🇸" },
    { name: "United States (Cayman)", timezone: "America/Cayman", flag: "🇺🇸" },
    { name: "United States (Chicago)", timezone: "America/Chicago", flag: "🇺🇸" },
    { name: "United States (Chihuahua)", timezone: "America/Chihuahua", flag: "🇺🇸" },
    { name: "United States (Ciudad Juarez)", timezone: "America/Ciudad_Juarez", flag: "🇺🇸" },
    { name: "United States (Coral Harbour)", timezone: "America/Coral_Harbour", flag: "🇺🇸" },
    { name: "United States (Cordoba)", timezone: "America/Cordoba", flag: "🇺🇸" },
    { name: "United States (Costa Rica)", timezone: "America/Costa_Rica", flag: "🇺🇸" },
    { name: "United States (Creston)", timezone: "America/Creston", flag: "🇺🇸" },
    { name: "United States (Cuiaba)", timezone: "America/Cuiaba", flag: "🇺🇸" },
    { name: "United States (Curacao)", timezone: "America/Curacao", flag: "🇺🇸" },
    { name: "United States (Danmarkshavn)", timezone: "America/Danmarkshavn", flag: "🇺🇸" },
    { name: "United States (Dawson)", timezone: "America/Dawson", flag: "🇺🇸" },
    { name: "United States (Dawson Creek)", timezone: "America/Dawson_Creek", flag: "🇺🇸" },
    { name: "United States (Denver)", timezone: "America/Denver", flag: "🇺🇸" },
    { name: "United States (Detroit)", timezone: "America/Detroit", flag: "🇺🇸" },
    { name: "United States (Dominica)", timezone: "America/Dominica", flag: "🇺🇸" },
    { name: "United States (Edmonton)", timezone: "America/Edmonton", flag: "🇺🇸" },
    { name: "United States (Eirunepe)", timezone: "America/Eirunepe", flag: "🇺🇸" },
    { name: "United States (El Salvador)", timezone: "America/El_Salvador", flag: "🇺🇸" },
    { name: "United States (Ensenada)", timezone: "America/Ensenada", flag: "🇺🇸" },
    { name: "United States (Fort Nelson)", timezone: "America/Fort_Nelson", flag: "🇺🇸" },
    { name: "United States (Fort Wayne)", timezone: "America/Fort_Wayne", flag: "🇺🇸" },
    { name: "United States (Fortaleza)", timezone: "America/Fortaleza", flag: "🇺🇸" },
    { name: "United States (Glace Bay)", timezone: "America/Glace_Bay", flag: "🇺🇸" },
    { name: "United States (Godthab)", timezone: "America/Godthab", flag: "🇺🇸" },
    { name: "United States (Goose Bay)", timezone: "America/Goose_Bay", flag: "🇺🇸" },
    { name: "United States (Grand Turk)", timezone: "America/Grand_Turk", flag: "🇺🇸" },
    { name: "United States (Grenada)", timezone: "America/Grenada", flag: "🇺🇸" },
    { name: "United States (Guadeloupe)", timezone: "America/Guadeloupe", flag: "🇺🇸" },
    { name: "United States (Guatemala)", timezone: "America/Guatemala", flag: "🇺🇸" },
    { name: "United States (Guayaquil)", timezone: "America/Guayaquil", flag: "🇺🇸" },
    { name: "United States (Guyana)", timezone: "America/Guyana", flag: "🇺🇸" },
    { name: "United States (Halifax)", timezone: "America/Halifax", flag: "🇺🇸" },
    { name: "United States (Havana)", timezone: "America/Havana", flag: "🇺🇸" },
    { name: "United States (Hermosillo)", timezone: "America/Hermosillo", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Indianapolis", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Knox", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Marengo", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Petersburg", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Tell_City", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Vevay", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Vincennes", flag: "🇺🇸" },
    { name: "United States (Indiana)", timezone: "America/Indiana/Winamac", flag: "🇺🇸" },
    { name: "United States (Indianapolis)", timezone: "America/Indianapolis", flag: "🇺🇸" },
    { name: "United States (Inuvik)", timezone: "America/Inuvik", flag: "🇺🇸" },
    { name: "United States (Iqaluit)", timezone: "America/Iqaluit", flag: "🇺🇸" },
    { name: "United States (Jamaica)", timezone: "America/Jamaica", flag: "🇺🇸" },
    { name: "United States (Jujuy)", timezone: "America/Jujuy", flag: "🇺🇸" },
    { name: "United States (Juneau)", timezone: "America/Juneau", flag: "🇺🇸" },
    { name: "United States (Kentucky)", timezone: "America/Kentucky/Louisville", flag: "🇺🇸" },
    { name: "United States (Kentucky)", timezone: "America/Kentucky/Monticello", flag: "🇺🇸" },
    { name: "United States (Knox IN)", timezone: "America/Knox_IN", flag: "🇺🇸" },
    { name: "United States (Kralendijk)", timezone: "America/Kralendijk", flag: "🇺🇸" },
    { name: "United States (La Paz)", timezone: "America/La_Paz", flag: "🇺🇸" },
    { name: "United States (Lima)", timezone: "America/Lima", flag: "🇺🇸" },
    { name: "United States (Los Angeles)", timezone: "America/Los_Angeles", flag: "🇺🇸" },
    { name: "United States (Louisville)", timezone: "America/Louisville", flag: "🇺🇸" },
    { name: "United States (Lower Princes)", timezone: "America/Lower_Princes", flag: "🇺🇸" },
    { name: "United States (Maceio)", timezone: "America/Maceio", flag: "🇺🇸" },
    { name: "United States (Managua)", timezone: "America/Managua", flag: "🇺🇸" },
    { name: "United States (Manaus)", timezone: "America/Manaus", flag: "🇺🇸" },
    { name: "United States (Marigot)", timezone: "America/Marigot", flag: "🇺🇸" },
    { name: "United States (Martinique)", timezone: "America/Martinique", flag: "🇺🇸" },
    { name: "United States (Matamoros)", timezone: "America/Matamoros", flag: "🇺🇸" },
    { name: "United States (Mazatlan)", timezone: "America/Mazatlan", flag: "🇺🇸" },
    { name: "United States (Mendoza)", timezone: "America/Mendoza", flag: "🇺🇸" },
    { name: "United States (Menominee)", timezone: "America/Menominee", flag: "🇺🇸" },
    { name: "United States (Merida)", timezone: "America/Merida", flag: "🇺🇸" },
    { name: "United States (Metlakatla)", timezone: "America/Metlakatla", flag: "🇺🇸" },
    { name: "United States (Mexico City)", timezone: "America/Mexico_City", flag: "🇺🇸" },
    { name: "United States (Miquelon)", timezone: "America/Miquelon", flag: "🇺🇸" },
    { name: "United States (Moncton)", timezone: "America/Moncton", flag: "🇺🇸" },
    { name: "United States (Monterrey)", timezone: "America/Monterrey", flag: "🇺🇸" },
    { name: "United States (Montevideo)", timezone: "America/Montevideo", flag: "🇺🇸" },
    { name: "United States (Montreal)", timezone: "America/Montreal", flag: "🇺🇸" },
    { name: "United States (Montserrat)", timezone: "America/Montserrat", flag: "🇺🇸" },
    { name: "United States (Nassau)", timezone: "America/Nassau", flag: "🇺🇸" },
    { name: "United States (New York)", timezone: "America/New_York", flag: "🇺🇸" },
    { name: "United States (Nipigon)", timezone: "America/Nipigon", flag: "🇺🇸" },
    { name: "United States (Nome)", timezone: "America/Nome", flag: "🇺🇸" },
    { name: "United States (Noronha)", timezone: "America/Noronha", flag: "🇺🇸" },
    { name: "United States (North Dakota)", timezone: "America/North_Dakota/Beulah", flag: "🇺🇸" },
    { name: "United States (North Dakota)", timezone: "America/North_Dakota/Center", flag: "🇺🇸" },
    { name: "United States (North Dakota)", timezone: "America/North_Dakota/New_Salem", flag: "🇺🇸" },
    { name: "United States (Nuuk)", timezone: "America/Nuuk", flag: "🇺🇸" },
    { name: "United States (Ojinaga)", timezone: "America/Ojinaga", flag: "🇺🇸" },
    { name: "United States (Panama)", timezone: "America/Panama", flag: "🇺🇸" },
    { name: "United States (Pangnirtung)", timezone: "America/Pangnirtung", flag: "🇺🇸" },
    { name: "United States (Paramaribo)", timezone: "America/Paramaribo", flag: "🇺🇸" },
    { name: "United States (Phoenix)", timezone: "America/Phoenix", flag: "🇺🇸" },
    { name: "United States (Port-au-Prince)", timezone: "America/Port-au-Prince", flag: "🇺🇸" },
    { name: "United States (Port of Spain)", timezone: "America/Port_of_Spain", flag: "🇺🇸" },
    { name: "United States (Porto Acre)", timezone: "America/Porto_Acre", flag: "🇺🇸" },
    { name: "United States (Porto Velho)", timezone: "America/Porto_Velho", flag: "🇺🇸" },
    { name: "United States (Puerto Rico)", timezone: "America/Puerto_Rico", flag: "🇺🇸" },
    { name: "United States (Punta Arenas)", timezone: "America/Punta_Arenas", flag: "🇺🇸" },
    { name: "United States (Rainy River)", timezone: "America/Rainy_River", flag: "🇺🇸" },
    { name: "United States (Rankin Inlet)", timezone: "America/Rankin_Inlet", flag: "🇺🇸" },
    { name: "United States (Recife)", timezone: "America/Recife", flag: "🇺🇸" },
    { name: "United States (Regina)", timezone: "America/Regina", flag: "🇺🇸" },
    { name: "United States (Resolute)", timezone: "America/Resolute", flag: "🇺🇸" },
    { name: "United States (Rio Branco)", timezone: "America/Rio_Branco", flag: "🇺🇸" },
    { name: "United States (Rosario)", timezone: "America/Rosario", flag: "🇺🇸" },
    { name: "United States (Santa Isabel)", timezone: "America/Santa_Isabel", flag: "🇺🇸" },
    { name: "United States (Santarem)", timezone: "America/Santarem", flag: "🇺🇸" },
    { name: "United States (Santiago)", timezone: "America/Santiago", flag: "🇺🇸" },
    { name: "United States (Santo Domingo)", timezone: "America/Santo_Domingo", flag: "🇺🇸" },
    { name: "United States (Sao Paulo)", timezone: "America/Sao_Paulo", flag: "🇺🇸" },
    { name: "United States (Scoresbysund)", timezone: "America/Scoresbysund", flag: "🇺🇸" },
    { name: "United States (Shiprock)", timezone: "America/Shiprock", flag: "🇺🇸" },
    { name: "United States (Sitka)", timezone: "America/Sitka", flag: "🇺🇸" },
    { name: "United States (St Barthelemy)", timezone: "America/St_Barthelemy", flag: "🇺🇸" },
    { name: "United States (St Johns)", timezone: "America/St_Johns", flag: "🇺🇸" },
    { name: "United States (St Kitts)", timezone: "America/St_Kitts", flag: "🇺🇸" },
    { name: "United States (St Lucia)", timezone: "America/St_Lucia", flag: "🇺🇸" },
    { name: "United States (St Thomas)", timezone: "America/St_Thomas", flag: "🇺🇸" },
    { name: "United States (St Vincent)", timezone: "America/St_Vincent", flag: "🇺🇸" },
    { name: "United States (Swift Current)", timezone: "America/Swift_Current", flag: "🇺🇸" },
    { name: "United States (Tegucigalpa)", timezone: "America/Tegucigalpa", flag: "🇺🇸" },
    { name: "United States (Thule)", timezone: "America/Thule", flag: "🇺🇸" },
    { name: "United States (Thunder Bay)", timezone: "America/Thunder_Bay", flag: "🇺🇸" },
    { name: "United States (Tijuana)", timezone: "America/Tijuana", flag: "🇺🇸" },
    { name: "United States (Toronto)", timezone: "America/Toronto", flag: "🇺🇸" },
    { name: "United States (Tortola)", timezone: "America/Tortola", flag: "🇺🇸" },
    { name: "United States (Vancouver)", timezone: "America/Vancouver", flag: "🇺🇸" },
    { name: "United States (Virgin)", timezone: "America/Virgin", flag: "🇺🇸" },
    { name: "United States (Whitehorse)", timezone: "America/Whitehorse", flag: "🇺🇸" },
    { name: "United States (Winnipeg)", timezone: "America/Winnipeg", flag: "🇺🇸" },
    { name: "United States (Yakutat)", timezone: "America/Yakutat", flag: "🇺🇸" },
    { name: "United States (Yellowknife)", timezone: "America/Yellowknife", flag: "🇺🇸" },
    { name: "Antarctica (Casey)", timezone: "Antarctica/Casey", flag: "🇦🇶" },
    { name: "Antarctica (Davis)", timezone: "Antarctica/Davis", flag: "🇦🇶" },
    { name: "Antarctica (DumontDUrville)", timezone: "Antarctica/DumontDUrville", flag: "🇦🇶" },
    { name: "Antarctica (Macquarie)", timezone: "Antarctica/Macquarie", flag: "🇦🇶" },
    { name: "Antarctica (Mawson)", timezone: "Antarctica/Mawson", flag: "🇦🇶" },
    { name: "Antarctica (McMurdo)", timezone: "Antarctica/McMurdo", flag: "🇦🇶" },
    { name: "Antarctica (Palmer)", timezone: "Antarctica/Palmer", flag: "🇦🇶" },
    { name: "Antarctica (Rothera)", timezone: "Antarctica/Rothera", flag: "🇦🇶" },
    { name: "Antarctica (South Pole)", timezone: "Antarctica/South_Pole", flag: "🇦🇶" },
    { name: "Antarctica (Syowa)", timezone: "Antarctica/Syowa", flag: "🇦🇶" },
    { name: "Antarctica (Troll)", timezone: "Antarctica/Troll", flag: "🇦🇶" },
    { name: "Antarctica (Vostok)", timezone: "Antarctica/Vostok", flag: "🇦🇶" },
    { name: "Norway (Longyearbyen)", timezone: "Arctic/Longyearbyen", flag: "🇳🇴" },
    { name: "China (Aden)", timezone: "Asia/Aden", flag: "🇨🇳" },
    { name: "China (Almaty)", timezone: "Asia/Almaty", flag: "🇨🇳" },
    { name: "China (Amman)", timezone: "Asia/Amman", flag: "🇨🇳" },
    { name: "China (Anadyr)", timezone: "Asia/Anadyr", flag: "🇨🇳" },
    { name: "China (Aqtau)", timezone: "Asia/Aqtau", flag: "🇨🇳" },
    { name: "China (Aqtobe)", timezone: "Asia/Aqtobe", flag: "🇨🇳" },
    { name: "China (Ashgabat)", timezone: "Asia/Ashgabat", flag: "🇨🇳" },
    { name: "China (Ashkhabad)", timezone: "Asia/Ashkhabad", flag: "🇨🇳" },
    { name: "China (Atyrau)", timezone: "Asia/Atyrau", flag: "🇨🇳" },
    { name: "China (Baghdad)", timezone: "Asia/Baghdad", flag: "🇨🇳" },
    { name: "China (Bahrain)", timezone: "Asia/Bahrain", flag: "🇨🇳" },
    { name: "China (Baku)", timezone: "Asia/Baku", flag: "🇨🇳" },
    { name: "China (Bangkok)", timezone: "Asia/Bangkok", flag: "🇨🇳" },
    { name: "China (Barnaul)", timezone: "Asia/Barnaul", flag: "🇨🇳" },
    { name: "China (Beirut)", timezone: "Asia/Beirut", flag: "🇨🇳" },
    { name: "China (Bishkek)", timezone: "Asia/Bishkek", flag: "🇨🇳" },
    { name: "China (Brunei)", timezone: "Asia/Brunei", flag: "🇨🇳" },
    { name: "China (Calcutta)", timezone: "Asia/Calcutta", flag: "🇨🇳" },
    { name: "China (Chita)", timezone: "Asia/Chita", flag: "🇨🇳" },
    { name: "China (Choibalsan)", timezone: "Asia/Choibalsan", flag: "🇨🇳" },
    { name: "China (Chongqing)", timezone: "Asia/Chongqing", flag: "🇨🇳" },
    { name: "China (Chungking)", timezone: "Asia/Chungking", flag: "🇨🇳" },
    { name: "China (Colombo)", timezone: "Asia/Colombo", flag: "🇨🇳" },
    { name: "China (Dacca)", timezone: "Asia/Dacca", flag: "🇨🇳" },
    { name: "China (Damascus)", timezone: "Asia/Damascus", flag: "🇨🇳" },
    { name: "China (Dhaka)", timezone: "Asia/Dhaka", flag: "🇨🇳" },
    { name: "China (Dili)", timezone: "Asia/Dili", flag: "🇨🇳" },
    { name: "China (Dubai)", timezone: "Asia/Dubai", flag: "🇨🇳" },
    { name: "China (Dushanbe)", timezone: "Asia/Dushanbe", flag: "🇨🇳" },
    { name: "China (Famagusta)", timezone: "Asia/Famagusta", flag: "🇨🇳" },
    { name: "China (Gaza)", timezone: "Asia/Gaza", flag: "🇨🇳" },
    { name: "China (Harbin)", timezone: "Asia/Harbin", flag: "🇨🇳" },
    { name: "China (Hebron)", timezone: "Asia/Hebron", flag: "🇨🇳" },
    { name: "China (Ho Chi Minh)", timezone: "Asia/Ho_Chi_Minh", flag: "🇨🇳" },
    { name: "China (Hong Kong)", timezone: "Asia/Hong_Kong", flag: "🇨🇳" },
    { name: "China (Hovd)", timezone: "Asia/Hovd", flag: "🇨🇳" },
    { name: "China (Irkutsk)", timezone: "Asia/Irkutsk", flag: "🇨🇳" },
    { name: "China (Istanbul)", timezone: "Asia/Istanbul", flag: "🇨🇳" },
    { name: "China (Jakarta)", timezone: "Asia/Jakarta", flag: "🇨🇳" },
    { name: "China (Jayapura)", timezone: "Asia/Jayapura", flag: "🇨🇳" },
    { name: "China (Jerusalem)", timezone: "Asia/Jerusalem", flag: "🇨🇳" },
    { name: "China (Kabul)", timezone: "Asia/Kabul", flag: "🇨🇳" },
    { name: "China (Kamchatka)", timezone: "Asia/Kamchatka", flag: "🇨🇳" },
    { name: "China (Karachi)", timezone: "Asia/Karachi", flag: "🇨🇳" },
    { name: "China (Kashgar)", timezone: "Asia/Kashgar", flag: "🇨🇳" },
    { name: "China (Kathmandu)", timezone: "Asia/Kathmandu", flag: "🇨🇳" },
    { name: "China (Katmandu)", timezone: "Asia/Katmandu", flag: "🇨🇳" },
    { name: "China (Khandyga)", timezone: "Asia/Khandyga", flag: "🇨🇳" },
    { name: "China (Kolkata)", timezone: "Asia/Kolkata", flag: "🇨🇳" },
    { name: "China (Krasnoyarsk)", timezone: "Asia/Krasnoyarsk", flag: "🇨🇳" },
    { name: "China (Kuala Lumpur)", timezone: "Asia/Kuala_Lumpur", flag: "🇨🇳" },
    { name: "China (Kuching)", timezone: "Asia/Kuching", flag: "🇨🇳" },
    { name: "China (Kuwait)", timezone: "Asia/Kuwait", flag: "🇨🇳" },
    { name: "China (Macao)", timezone: "Asia/Macao", flag: "🇨🇳" },
    { name: "China (Macau)", timezone: "Asia/Macau", flag: "🇨🇳" },
    { name: "China (Magadan)", timezone: "Asia/Magadan", flag: "🇨🇳" },
    { name: "China (Makassar)", timezone: "Asia/Makassar", flag: "🇨🇳" },
    { name: "China (Manila)", timezone: "Asia/Manila", flag: "🇨🇳" },
    { name: "China (Muscat)", timezone: "Asia/Muscat", flag: "🇨🇳" },
    { name: "China (Nicosia)", timezone: "Asia/Nicosia", flag: "🇨🇳" },
    { name: "China (Novokuznetsk)", timezone: "Asia/Novokuznetsk", flag: "🇨🇳" },
    { name: "China (Novosibirsk)", timezone: "Asia/Novosibirsk", flag: "🇨🇳" },
    { name: "China (Omsk)", timezone: "Asia/Omsk", flag: "🇨🇳" },
    { name: "China (Oral)", timezone: "Asia/Oral", flag: "🇨🇳" },
    { name: "China (Phnom Penh)", timezone: "Asia/Phnom_Penh", flag: "🇨🇳" },
    { name: "China (Pontianak)", timezone: "Asia/Pontianak", flag: "🇨🇳" },
    { name: "China (Pyongyang)", timezone: "Asia/Pyongyang", flag: "🇨🇳" },
    { name: "China (Qatar)", timezone: "Asia/Qatar", flag: "🇨🇳" },
    { name: "China (Qostanay)", timezone: "Asia/Qostanay", flag: "🇨🇳" },
    { name: "China (Qyzylorda)", timezone: "Asia/Qyzylorda", flag: "🇨🇳" },
    { name: "China (Rangoon)", timezone: "Asia/Rangoon", flag: "🇨🇳" },
    { name: "China (Riyadh)", timezone: "Asia/Riyadh", flag: "🇨🇳" },
    { name: "China (Saigon)", timezone: "Asia/Saigon", flag: "🇨🇳" },
    { name: "China (Sakhalin)", timezone: "Asia/Sakhalin", flag: "🇨🇳" },
    { name: "China (Samarkand)", timezone: "Asia/Samarkand", flag: "🇨🇳" },
    { name: "China (Seoul)", timezone: "Asia/Seoul", flag: "🇨🇳" },
    { name: "China (Shanghai)", timezone: "Asia/Shanghai", flag: "🇨🇳" },
    { name: "China (Singapore)", timezone: "Asia/Singapore", flag: "🇨🇳" },
    { name: "China (Srednekolymsk)", timezone: "Asia/Srednekolymsk", flag: "🇨🇳" },
    { name: "China (Taipei)", timezone: "Asia/Taipei", flag: "🇨🇳" },
    { name: "China (Tashkent)", timezone: "Asia/Tashkent", flag: "🇨🇳" },
    { name: "China (Tbilisi)", timezone: "Asia/Tbilisi", flag: "🇨🇳" },
    { name: "China (Tehran)", timezone: "Asia/Tehran", flag: "🇨🇳" },
    { name: "China (Tel Aviv)", timezone: "Asia/Tel_Aviv", flag: "🇨🇳" },
    { name: "China (Thimbu)", timezone: "Asia/Thimbu", flag: "🇨🇳" },
    { name: "China (Thimphu)", timezone: "Asia/Thimphu", flag: "🇨🇳" },
    { name: "China (Tokyo)", timezone: "Asia/Tokyo", flag: "🇨🇳" },
    { name: "China (Tomsk)", timezone: "Asia/Tomsk", flag: "🇨🇳" },
    { name: "China (Ujung Pandang)", timezone: "Asia/Ujung_Pandang", flag: "🇨🇳" },
    { name: "China (Ulaanbaatar)", timezone: "Asia/Ulaanbaatar", flag: "🇨🇳" },
    { name: "China (Ulan Bator)", timezone: "Asia/Ulan_Bator", flag: "🇨🇳" },
    { name: "China (Urumqi)", timezone: "Asia/Urumqi", flag: "🇨🇳" },
    { name: "China (Ust-Nera)", timezone: "Asia/Ust-Nera", flag: "🇨🇳" },
    { name: "China (Vientiane)", timezone: "Asia/Vientiane", flag: "🇨🇳" },
    { name: "China (Vladivostok)", timezone: "Asia/Vladivostok", flag: "🇨🇳" },
    { name: "China (Yakutsk)", timezone: "Asia/Yakutsk", flag: "🇨🇳" },
    { name: "China (Yangon)", timezone: "Asia/Yangon", flag: "🇨🇳" },
    { name: "China (Yekaterinburg)", timezone: "Asia/Yekaterinburg", flag: "🇨🇳" },
    { name: "China (Yerevan)", timezone: "Asia/Yerevan", flag: "🇨🇳" },
    { name: "Iceland (Azores)", timezone: "Atlantic/Azores", flag: "🇮🇸" },
    { name: "Iceland (Bermuda)", timezone: "Atlantic/Bermuda", flag: "🇮🇸" },
    { name: "Iceland (Canary)", timezone: "Atlantic/Canary", flag: "🇮🇸" },
    { name: "Iceland (Cape Verde)", timezone: "Atlantic/Cape_Verde", flag: "🇮🇸" },
    { name: "Iceland (Faeroe)", timezone: "Atlantic/Faeroe", flag: "🇮🇸" },
    { name: "Iceland (Faroe)", timezone: "Atlantic/Faroe", flag: "🇮🇸" },
    { name: "Iceland (Jan Mayen)", timezone: "Atlantic/Jan_Mayen", flag: "🇮🇸" },
    { name: "Iceland (Madeira)", timezone: "Atlantic/Madeira", flag: "🇮🇸" },
    { name: "Iceland (Reykjavik)", timezone: "Atlantic/Reykjavik", flag: "🇮🇸" },
    { name: "Iceland (South Georgia)", timezone: "Atlantic/South_Georgia", flag: "🇮🇸" },
    { name: "Iceland (St Helena)", timezone: "Atlantic/St_Helena", flag: "🇮🇸" },
    { name: "Iceland (Stanley)", timezone: "Atlantic/Stanley", flag: "🇮🇸" },
    { name: "Australia (ACT)", timezone: "Australia/ACT", flag: "🇦🇺" },
    { name: "Australia (Adelaide)", timezone: "Australia/Adelaide", flag: "🇦🇺" },
    { name: "Australia (Brisbane)", timezone: "Australia/Brisbane", flag: "🇦🇺" },
    { name: "Australia (Broken Hill)", timezone: "Australia/Broken_Hill", flag: "🇦🇺" },
    { name: "Australia (Canberra)", timezone: "Australia/Canberra", flag: "🇦🇺" },
    { name: "Australia (Currie)", timezone: "Australia/Currie", flag: "🇦🇺" },
    { name: "Australia (Darwin)", timezone: "Australia/Darwin", flag: "🇦🇺" },
    { name: "Australia (Eucla)", timezone: "Australia/Eucla", flag: "🇦🇺" },
    { name: "Australia (Hobart)", timezone: "Australia/Hobart", flag: "🇦🇺" },
    { name: "Australia (LHI)", timezone: "Australia/LHI", flag: "🇦🇺" },
    { name: "Australia (Lindeman)", timezone: "Australia/Lindeman", flag: "🇦🇺" },
    { name: "Australia (Lord Howe)", timezone: "Australia/Lord_Howe", flag: "🇦🇺" },
    { name: "Australia (Melbourne)", timezone: "Australia/Melbourne", flag: "🇦🇺" },
    { name: "Australia (NSW)", timezone: "Australia/NSW", flag: "🇦🇺" },
    { name: "Australia (North)", timezone: "Australia/North", flag: "🇦🇺" },
    { name: "Australia (Perth)", timezone: "Australia/Perth", flag: "🇦🇺" },
    { name: "Australia (Queensland)", timezone: "Australia/Queensland", flag: "🇦🇺" },
    { name: "Australia (South)", timezone: "Australia/South", flag: "🇦🇺" },
    { name: "Australia (Sydney)", timezone: "Australia/Sydney", flag: "🇦🇺" },
    { name: "Australia (Tasmania)", timezone: "Australia/Tasmania", flag: "🇦🇺" },
    { name: "Australia (Victoria)", timezone: "Australia/Victoria", flag: "🇦🇺" },
    { name: "Australia (West)", timezone: "Australia/West", flag: "🇦🇺" },
    { name: "Australia (Yancowinna)", timezone: "Australia/Yancowinna", flag: "🇦🇺" },
    { name: "Brazil (Acre)", timezone: "Brazil/Acre", flag: "" },
    { name: "Brazil (DeNoronha)", timezone: "Brazil/DeNoronha", flag: "" },
    { name: "Brazil (East)", timezone: "Brazil/East", flag: "" },
    { name: "Brazil (West)", timezone: "Brazil/West", flag: "" },
    { name: "Canada (Atlantic)", timezone: "Canada/Atlantic", flag: "" },
    { name: "Canada (Central)", timezone: "Canada/Central", flag: "" },
    { name: "Canada (Eastern)", timezone: "Canada/Eastern", flag: "" },
    { name: "Canada (Mountain)", timezone: "Canada/Mountain", flag: "" },
    { name: "Canada (Newfoundland)", timezone: "Canada/Newfoundland", flag: "" },
    { name: "Canada (Pacific)", timezone: "Canada/Pacific", flag: "" },
    { name: "Canada (Saskatchewan)", timezone: "Canada/Saskatchewan", flag: "" },
    { name: "Canada (Yukon)", timezone: "Canada/Yukon", flag: "" },
    { name: "Chile (Continental)", timezone: "Chile/Continental", flag: "" },
    { name: "Chile (EasterIsland)", timezone: "Chile/EasterIsland", flag: "" },
    { name: "Etc (GMT)", timezone: "Etc/GMT", flag: "" },
    { name: "Etc (GMT+0)", timezone: "Etc/GMT+0", flag: "" },
    { name: "Etc (GMT+1)", timezone: "Etc/GMT+1", flag: "" },
    { name: "Etc (GMT+10)", timezone: "Etc/GMT+10", flag: "" },
    { name: "Etc (GMT+11)", timezone: "Etc/GMT+11", flag: "" },
    { name: "Etc (GMT+12)", timezone: "Etc/GMT+12", flag: "" },
    { name: "Etc (GMT+2)", timezone: "Etc/GMT+2", flag: "" },
    { name: "Etc (GMT+3)", timezone: "Etc/GMT+3", flag: "" },
    { name: "Etc (GMT+4)", timezone: "Etc/GMT+4", flag: "" },
    { name: "Etc (GMT+5)", timezone: "Etc/GMT+5", flag: "" },
    { name: "Etc (GMT+6)", timezone: "Etc/GMT+6", flag: "" },
    { name: "Etc (GMT+7)", timezone: "Etc/GMT+7", flag: "" },
    { name: "Etc (GMT+8)", timezone: "Etc/GMT+8", flag: "" },
    { name: "Etc (GMT+9)", timezone: "Etc/GMT+9", flag: "" },
    { name: "Etc (GMT-0)", timezone: "Etc/GMT-0", flag: "" },
    { name: "Etc (GMT-1)", timezone: "Etc/GMT-1", flag: "" },
    { name: "Etc (GMT-10)", timezone: "Etc/GMT-10", flag: "" },
    { name: "Etc (GMT-11)", timezone: "Etc/GMT-11", flag: "" },
    { name: "Etc (GMT-12)", timezone: "Etc/GMT-12", flag: "" },
    { name: "Etc (GMT-13)", timezone: "Etc/GMT-13", flag: "" },
    { name: "Etc (GMT-14)", timezone: "Etc/GMT-14", flag: "" },
    { name: "Etc (GMT-2)", timezone: "Etc/GMT-2", flag: "" },
    { name: "Etc (GMT-3)", timezone: "Etc/GMT-3", flag: "" },
    { name: "Etc (GMT-4)", timezone: "Etc/GMT-4", flag: "" },
    { name: "Etc (GMT-5)", timezone: "Etc/GMT-5", flag: "" },
    { name: "Etc (GMT-6)", timezone: "Etc/GMT-6", flag: "" },
    { name: "Etc (GMT-7)", timezone: "Etc/GMT-7", flag: "" },
    { name: "Etc (GMT-8)", timezone: "Etc/GMT-8", flag: "" },
    { name: "Etc (GMT-9)", timezone: "Etc/GMT-9", flag: "" },
    { name: "Etc (GMT0)", timezone: "Etc/GMT0", flag: "" },
    { name: "Etc (Greenwich)", timezone: "Etc/Greenwich", flag: "" },
    { name: "Etc (UCT)", timezone: "Etc/UCT", flag: "" },
    { name: "Etc (UTC)", timezone: "Etc/UTC", flag: "" },
    { name: "Etc (Universal)", timezone: "Etc/Universal", flag: "" },
    { name: "Etc (Zulu)", timezone: "Etc/Zulu", flag: "" },
    { name: "Europe (Amsterdam)", timezone: "Europe/Amsterdam", flag: "" },
    { name: "Europe (Andorra)", timezone: "Europe/Andorra", flag: "" },
    { name: "Europe (Astrakhan)", timezone: "Europe/Astrakhan", flag: "" },
    { name: "Europe (Athens)", timezone: "Europe/Athens", flag: "" },
    { name: "Europe (Belfast)", timezone: "Europe/Belfast", flag: "" },
    { name: "Europe (Belgrade)", timezone: "Europe/Belgrade", flag: "" },
    { name: "Europe (Berlin)", timezone: "Europe/Berlin", flag: "" },
    { name: "Europe (Bratislava)", timezone: "Europe/Bratislava", flag: "" },
    { name: "Europe (Brussels)", timezone: "Europe/Brussels", flag: "" },
    { name: "Europe (Bucharest)", timezone: "Europe/Bucharest", flag: "" },
    { name: "Europe (Budapest)", timezone: "Europe/Budapest", flag: "" },
    { name: "Europe (Busingen)", timezone: "Europe/Busingen", flag: "" },
    { name: "Europe (Chisinau)", timezone: "Europe/Chisinau", flag: "" },
    { name: "Europe (Copenhagen)", timezone: "Europe/Copenhagen", flag: "" },
    { name: "Europe (Dublin)", timezone: "Europe/Dublin", flag: "" },
    { name: "Europe (Gibraltar)", timezone: "Europe/Gibraltar", flag: "" },
    { name: "Europe (Guernsey)", timezone: "Europe/Guernsey", flag: "" },
    { name: "Europe (Helsinki)", timezone: "Europe/Helsinki", flag: "" },
    { name: "Europe (Isle of Man)", timezone: "Europe/Isle_of_Man", flag: "" },
    { name: "Europe (Istanbul)", timezone: "Europe/Istanbul", flag: "" },
    { name: "Europe (Jersey)", timezone: "Europe/Jersey", flag: "" },
    { name: "Europe (Kaliningrad)", timezone: "Europe/Kaliningrad", flag: "" },
    { name: "Europe (Kiev)", timezone: "Europe/Kiev", flag: "" },
    { name: "Europe (Kirov)", timezone: "Europe/Kirov", flag: "" },
    { name: "Europe (Kyiv)", timezone: "Europe/Kyiv", flag: "" },
    { name: "Europe (Lisbon)", timezone: "Europe/Lisbon", flag: "" },
    { name: "Europe (Ljubljana)", timezone: "Europe/Ljubljana", flag: "" },
    { name: "Europe (London)", timezone: "Europe/London", flag: "" },
    { name: "Europe (Luxembourg)", timezone: "Europe/Luxembourg", flag: "" },
    { name: "Europe (Madrid)", timezone: "Europe/Madrid", flag: "" },
    { name: "Europe (Malta)", timezone: "Europe/Malta", flag: "" },
    { name: "Europe (Mariehamn)", timezone: "Europe/Mariehamn", flag: "" },
    { name: "Europe (Minsk)", timezone: "Europe/Minsk", flag: "" },
    { name: "Europe (Monaco)", timezone: "Europe/Monaco", flag: "" },
    { name: "Europe (Moscow)", timezone: "Europe/Moscow", flag: "" },
    { name: "Europe (Nicosia)", timezone: "Europe/Nicosia", flag: "" },
    { name: "Europe (Oslo)", timezone: "Europe/Oslo", flag: "" },
    { name: "Europe (Paris)", timezone: "Europe/Paris", flag: "" },
    { name: "Europe (Podgorica)", timezone: "Europe/Podgorica", flag: "" },
    { name: "Europe (Prague)", timezone: "Europe/Prague", flag: "" },
    { name: "Europe (Riga)", timezone: "Europe/Riga", flag: "" },
    { name: "Europe (Rome)", timezone: "Europe/Rome", flag: "" },
    { name: "Europe (Samara)", timezone: "Europe/Samara", flag: "" },
    { name: "Europe (San Marino)", timezone: "Europe/San_Marino", flag: "" },
    { name: "Europe (Sarajevo)", timezone: "Europe/Sarajevo", flag: "" },
    { name: "Europe (Saratov)", timezone: "Europe/Saratov", flag: "" },
    { name: "Europe (Simferopol)", timezone: "Europe/Simferopol", flag: "" },
    { name: "Europe (Skopje)", timezone: "Europe/Skopje", flag: "" },
    { name: "Europe (Sofia)", timezone: "Europe/Sofia", flag: "" },
    { name: "Europe (Stockholm)", timezone: "Europe/Stockholm", flag: "" },
    { name: "Europe (Tallinn)", timezone: "Europe/Tallinn", flag: "" },
    { name: "Europe (Tirane)", timezone: "Europe/Tirane", flag: "" },
    { name: "Europe (Tiraspol)", timezone: "Europe/Tiraspol", flag: "" },
    { name: "Europe (Ulyanovsk)", timezone: "Europe/Ulyanovsk", flag: "" },
    { name: "Europe (Uzhgorod)", timezone: "Europe/Uzhgorod", flag: "" },
    { name: "Europe (Vaduz)", timezone: "Europe/Vaduz", flag: "" },
    { name: "Europe (Vatican)", timezone: "Europe/Vatican", flag: "" },
    { name: "Europe (Vienna)", timezone: "Europe/Vienna", flag: "" },
    { name: "Europe (Vilnius)", timezone: "Europe/Vilnius", flag: "" },
    { name: "Europe (Volgograd)", timezone: "Europe/Volgograd", flag: "" },
    { name: "Europe (Warsaw)", timezone: "Europe/Warsaw", flag: "" },
    { name: "Europe (Zagreb)", timezone: "Europe/Zagreb", flag: "" },
    { name: "Europe (Zaporozhye)", timezone: "Europe/Zaporozhye", flag: "" },
    { name: "Europe (Zurich)", timezone: "Europe/Zurich", flag: "" },
    { name: "India (Antananarivo)", timezone: "Indian/Antananarivo", flag: "🇮🇳" },
    { name: "India (Chagos)", timezone: "Indian/Chagos", flag: "🇮🇳" },
    { name: "India (Christmas)", timezone: "Indian/Christmas", flag: "🇮🇳" },
    { name: "India (Cocos)", timezone: "Indian/Cocos", flag: "🇮🇳" },
    { name: "India (Comoro)", timezone: "Indian/Comoro", flag: "🇮🇳" },
    { name: "India (Kerguelen)", timezone: "Indian/Kerguelen", flag: "🇮🇳" },
    { name: "India (Mahe)", timezone: "Indian/Mahe", flag: "🇮🇳" },
    { name: "India (Maldives)", timezone: "Indian/Maldives", flag: "🇮🇳" },
    { name: "India (Mauritius)", timezone: "Indian/Mauritius", flag: "🇮🇳" },
    { name: "India (Mayotte)", timezone: "Indian/Mayotte", flag: "🇮🇳" },
    { name: "India (Reunion)", timezone: "Indian/Reunion", flag: "🇮🇳" },
    { name: "Mexico (BajaNorte)", timezone: "Mexico/BajaNorte", flag: "" },
    { name: "Mexico (BajaSur)", timezone: "Mexico/BajaSur", flag: "" },
    { name: "Mexico (General)", timezone: "Mexico/General", flag: "" },
    { name: "Australia (Apia)", timezone: "Pacific/Apia", flag: "🇦🇺" },
    { name: "Australia (Auckland)", timezone: "Pacific/Auckland", flag: "🇦🇺" },
    { name: "Australia (Bougainville)", timezone: "Pacific/Bougainville", flag: "🇦🇺" },
    { name: "Australia (Chatham)", timezone: "Pacific/Chatham", flag: "🇦🇺" },
    { name: "Australia (Chuuk)", timezone: "Pacific/Chuuk", flag: "🇦🇺" },
    { name: "Australia (Easter)", timezone: "Pacific/Easter", flag: "🇦🇺" },
    { name: "Australia (Efate)", timezone: "Pacific/Efate", flag: "🇦🇺" },
    { name: "Australia (Enderbury)", timezone: "Pacific/Enderbury", flag: "🇦🇺" },
    { name: "Australia (Fakaofo)", timezone: "Pacific/Fakaofo", flag: "🇦🇺" },
    { name: "Australia (Fiji)", timezone: "Pacific/Fiji", flag: "🇦🇺" },
    { name: "Australia (Funafuti)", timezone: "Pacific/Funafuti", flag: "🇦🇺" },
    { name: "Australia (Galapagos)", timezone: "Pacific/Galapagos", flag: "🇦🇺" },
    { name: "Australia (Gambier)", timezone: "Pacific/Gambier", flag: "🇦🇺" },
    { name: "Australia (Guadalcanal)", timezone: "Pacific/Guadalcanal", flag: "🇦🇺" },
    { name: "Australia (Guam)", timezone: "Pacific/Guam", flag: "🇦🇺" },
    { name: "Australia (Honolulu)", timezone: "Pacific/Honolulu", flag: "🇦🇺" },
    { name: "Australia (Johnston)", timezone: "Pacific/Johnston", flag: "🇦🇺" },
    { name: "Australia (Kanton)", timezone: "Pacific/Kanton", flag: "🇦🇺" },
    { name: "Australia (Kiritimati)", timezone: "Pacific/Kiritimati", flag: "🇦🇺" },
    { name: "Australia (Kosrae)", timezone: "Pacific/Kosrae", flag: "🇦🇺" },
    { name: "Australia (Kwajalein)", timezone: "Pacific/Kwajalein", flag: "🇦🇺" },
    { name: "Australia (Majuro)", timezone: "Pacific/Majuro", flag: "🇦🇺" },
    { name: "Australia (Marquesas)", timezone: "Pacific/Marquesas", flag: "🇦🇺" },
    { name: "Australia (Midway)", timezone: "Pacific/Midway", flag: "🇦🇺" },
    { name: "Australia (Nauru)", timezone: "Pacific/Nauru", flag: "🇦🇺" },
    { name: "Australia (Niue)", timezone: "Pacific/Niue", flag: "🇦🇺" },
    { name: "Australia (Norfolk)", timezone: "Pacific/Norfolk", flag: "🇦🇺" },
    { name: "Australia (Noumea)", timezone: "Pacific/Noumea", flag: "🇦🇺" },
    { name: "Australia (Pago Pago)", timezone: "Pacific/Pago_Pago", flag: "🇦🇺" },
    { name: "Australia (Palau)", timezone: "Pacific/Palau", flag: "🇦🇺" },
    { name: "Australia (Pitcairn)", timezone: "Pacific/Pitcairn", flag: "🇦🇺" },
    { name: "Australia (Pohnpei)", timezone: "Pacific/Pohnpei", flag: "🇦🇺" },
    { name: "Australia (Ponape)", timezone: "Pacific/Ponape", flag: "🇦🇺" },
    { name: "Australia (Port Moresby)", timezone: "Pacific/Port_Moresby", flag: "🇦🇺" },
    { name: "Australia (Rarotonga)", timezone: "Pacific/Rarotonga", flag: "🇦🇺" },
    { name: "Australia (Saipan)", timezone: "Pacific/Saipan", flag: "🇦🇺" },
    { name: "Australia (Samoa)", timezone: "Pacific/Samoa", flag: "🇦🇺" },
    { name: "Australia (Tahiti)", timezone: "Pacific/Tahiti", flag: "🇦🇺" },
    { name: "Australia (Tarawa)", timezone: "Pacific/Tarawa", flag: "🇦🇺" },
    { name: "Australia (Tongatapu)", timezone: "Pacific/Tongatapu", flag: "🇦🇺" },
    { name: "Australia (Truk)", timezone: "Pacific/Truk", flag: "🇦🇺" },
    { name: "Australia (Wake)", timezone: "Pacific/Wake", flag: "🇦🇺" },
    { name: "Australia (Wallis)", timezone: "Pacific/Wallis", flag: "🇦🇺" },
    { name: "Australia (Yap)", timezone: "Pacific/Yap", flag: "🇦🇺" },
    { name: "US (Alaska)", timezone: "US/Alaska", flag: "" },
    { name: "US (Aleutian)", timezone: "US/Aleutian", flag: "" },
    { name: "US (Arizona)", timezone: "US/Arizona", flag: "" },
    { name: "US (Central)", timezone: "US/Central", flag: "" },
    { name: "US (East-Indiana)", timezone: "US/East-Indiana", flag: "" },
    { name: "US (Eastern)", timezone: "US/Eastern", flag: "" },
    { name: "US (Hawaii)", timezone: "US/Hawaii", flag: "" },
    { name: "US (Indiana-Starke)", timezone: "US/Indiana-Starke", flag: "" },
    { name: "US (Michigan)", timezone: "US/Michigan", flag: "" },
    { name: "US (Mountain)", timezone: "US/Mountain", flag: "" },
    { name: "US (Pacific)", timezone: "US/Pacific", flag: "" },
    { name: "US (Samoa)", timezone: "US/Samoa", flag: "" },
];
